language: node_js
node_js:
  - lts/boron
  - node
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
script:
  - npm test
  - npm run test-browser -- --browser=firefox
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: A605hzBmhlOLwZdH35BCUfciruZJrHYvU2dWh4hkYvlUUbvxzmZOMyi3JoCLMmGzsnWuX6sInQUIXdaUX5MPD9DC+xcNtoWKz03Ws0AHGuw8lfO/qZH0Egr5vhvxGeqXJLMAP+VhducRW0ti5/zZZSjjIUjLM5AGGr2DGql8U5urE62TZ0/3KU7jUriqjP+GH3EVwNxXOMxT/Bq90HRUzxn6H0xNpEHUMqflJ8S8VqfUNgkZW36WM4FTj5VZIr/m5V6oLuHsVRJctxvb1CjttxLORql2OXppsAqlvE78Muu8ulqQidqWDf5gO6vq3N6/E/dx8+7Zo0WeCPVD3ym1GHAp/i1v4DiA6rEnku8Rl5GzhaKKezRLQKuS+2+mQFDmB2jDa4QYGeEDTK50lbyfUtmyfJNertCwwMy4SMn3TV5bj02EtWQ3WErYKF7qLSJfHi2oMyl1hiscDrF1ge+c6bTsW9iIVu3Eta1hOKlnginetJilAxX+CqTxPbRrtX2ecp4uj1+M9H8pXaSdxcEgLu/M6cRyGEdnhtraU19uSODpYjUj90P0shAz1XXz2vddLj9JHzZoL39Wf9BSl2g32u4K5dAiFLcTL1/3dQ1NxA/OSvC70Gxds7s7PpGzo1hBmyEByfbUZP/TSL/ezbQGeglOEsizmPTbSUKrZSfoGa8=
  file:
    - "parse-entities.js"
    - "parse-entities.min.js"
  on:
    tags: true
